[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "22"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[redirects]]
  from = "/"
  to = "/en"
  status = 301
  force = true
